import { createStitches } from "@stitches/react";
import {
  amber,
  amberA,
  amberDark,
  amberDarkA,
  blackA,
  blue,
  blueA,
  blueDark,
  blueDarkA,
  bronze,
  bronzeA,
  bronzeDark,
  bronzeDarkA,
  brown,
  brownA,
  brownDark,
  brownDarkA,
  crimson,
  crimsonA,
  crimsonDark,
  crimsonDarkA,
  cyan,
  cyanA,
  cyanDark,
  cyanDarkA,
  gold,
  goldA,
  goldDark,
  goldDarkA,
  grass,
  grassA,
  grassDark,
  grassDarkA,
  gray,
  grayA,
  grayDark,
  grayDarkA,
  green,
  greenA,
  greenDark,
  greenDarkA,
  indigo,
  indigoA,
  indigoDark,
  indigoDarkA,
  lime,
  limeA,
  limeDark,
  limeDarkA,
  mauve,
  mauveA,
  mauveDark,
  mauveDarkA,
  mint,
  mintA,
  mintDark,
  mintDarkA,
  olive,
  oliveA,
  oliveDark,
  oliveDarkA,
  orange,
  orangeA,
  orangeDark,
  orangeDarkA,
  pink,
  pinkA,
  pinkDark,
  pinkDarkA,
  plum,
  plumA,
  plumDark,
  plumDarkA,
  purple,
  purpleA,
  purpleDark,
  purpleDarkA,
  red,
  redA,
  redDark,
  redDarkA,
  sage,
  sageA,
  sageDark,
  sageDarkA,
  sand,
  sandA,
  sandDark,
  sandDarkA,
  sky,
  skyA,
  skyDark,
  skyDarkA,
  slate,
  slateA,
  slateDark,
  slateDarkA,
  teal,
  tealA,
  tealDark,
  tealDarkA,
  tomato,
  tomatoA,
  tomatoDark,
  tomatoDarkA,
  violet,
  violetA,
  violetDark,
  violetDarkA,
  whiteA,
  yellow,
  yellowA,
  yellowDark,
  yellowDarkA,
} from "@radix-ui/colors";
import type * as Stitches from "@stitches/react";
export type { VariantProps } from "@stitches/react";
import * as figma from "./__generated__/figma-design-tokens";

const spacing = {
  0: "0px",
  1: "1px",
  2: "2px",
  3: "4px",
  4: "6px",
  5: "8px",
  6: "10px",
  7: "12px",
  8: "14px",
  9: "16px",
  10: "20px",
  11: "24px",
  12: "28px",
  13: "32px",
  14: "36px",
  15: "40px",
  16: "44px",
  17: "48px",
  18: "56px",
  19: "64px",
  20: "80px",
  21: "96px",
  22: "112px",
  23: "128px",
  24: "144px",
  25: "160px",
  26: "176px",
  27: "192px",
  28: "208px",
  29: "224px",
  30: "240px",
  31: "256px",
  32: "288px",
  33: "320px",
  34: "384px",
  35: "448px",
} as const;

const {
  styled,
  css,
  createTheme,
  getCssText,
  globalCss,
  keyframes,
  config,
  reset,
} = createStitches({
  theme: {
    colors: {
      ...gray,
      ...mauve,
      ...slate,
      ...sage,
      ...olive,
      ...sand,
      ...tomato,
      ...red,
      ...crimson,
      ...pink,
      ...plum,
      ...purple,
      ...violet,
      ...indigo,
      ...blue,
      ...sky,
      ...mint,
      ...cyan,
      ...teal,
      ...green,
      ...grass,
      ...lime,
      ...yellow,
      ...amber,
      ...orange,
      ...brown,
      ...bronze,
      ...gold,

      ...grayA,
      ...mauveA,
      ...slateA,
      ...sageA,
      ...oliveA,
      ...sandA,
      ...tomatoA,
      ...redA,
      ...crimsonA,
      ...pinkA,
      ...plumA,
      ...purpleA,
      ...violetA,
      ...indigoA,
      ...blueA,
      ...skyA,
      ...mintA,
      ...cyanA,
      ...tealA,
      ...greenA,
      ...grassA,
      ...limeA,
      ...yellowA,
      ...amberA,
      ...orangeA,
      ...brownA,
      ...bronzeA,
      ...goldA,

      ...whiteA,
      ...blackA,

      // Semantic colors
      hiContrast: "$slate12",
      loContrast: "$slate1",
      hint: "$slate9",
      muted: "$slate6",
      primary: "$blue10",
      canvas: "hsl(0 0% 93%)",
      panel: "white",
      panelOutline: "hsl(0deg 0% 0% / 10%)",
      transparentPanel: "hsl(0 0% 0% / 97%)",
      shadowLight: "hsl(206 22% 7% / 35%)",
      shadowDark: "hsl(206 22% 7% / 20%)",
      background: "$slate1",
      text: "$slate12",
      transparentExtreme: "transparent",

      ...figma.color,
    },
    fonts: {
      ...figma.fontFamilies,
      sans: figma.fontFamilies.inter,
      mono: figma.fontFamilies.robotoMono,
    },

    opacity: {
      1: "0.4",
    },
    spacing,

    /**
     * Use instead: textVariants / textStyles / <Text />
     */
    deprecatedFontSize: {
      1: "8px",
      2: "10px",
      3: "12px",
      // Legacy - don't use unless specified in Figma
      4: "14px",
      5: "19px",
      6: "21px",
      7: "27px",
      8: "35px",
      9: "59px",
    },

    /**
     * Use instead: textVariants / textStyles / <Text />
     */
    deprecatedLineHeight: {
      1: "8px",
      2: "12px",
      3: "16px",
      // Legacy - don't use unless specified in Figma
      4: "20px",
    },

    borderRadius: {
      1: "1px",
      2: "2px",
      3: "3px",
      4: "4px",
      5: "5px",
      6: "6px",
      7: "8px",
      round: "50%",
      pill: "9999px",
    },
    zIndices: {
      1: "100",
      2: "200",
      3: "300",
      4: "400",
      max: "999",
    },
    easing: {
      easeOutQuart: "cubic-bezier(0.25, 1, 0.5, 1)",
      easeOut: "cubic-bezier(0.16, 1, 0.3, 1)",
    },
    shadows: figma.boxShadow,
  },
  media: {
    tablet: "(min-width: 768px)",
    laptop: "(min-width: 1024px)",
    desktop: "(min-width: 1280px)",
    motion: "(prefers-reduced-motion)",
    hover: "(any-hover: hover)",
    dark: "(prefers-color-scheme: dark)",
    light: "(prefers-color-scheme: light)",
  },
  utils: {
    p: (value: Stitches.PropertyValue<"padding">) => ({
      padding: value,
    }),
    pt: (value: Stitches.PropertyValue<"paddingTop">) => ({
      paddingTop: value,
    }),
    pr: (value: Stitches.PropertyValue<"paddingRight">) => ({
      paddingRight: value,
    }),
    pb: (value: Stitches.PropertyValue<"paddingBottom">) => ({
      paddingBottom: value,
    }),
    pl: (value: Stitches.PropertyValue<"paddingLeft">) => ({
      paddingLeft: value,
    }),
    px: (value: Stitches.PropertyValue<"paddingLeft">) => ({
      paddingLeft: value,
      paddingRight: value,
    }),
    py: (value: Stitches.PropertyValue<"paddingTop">) => ({
      paddingTop: value,
      paddingBottom: value,
    }),

    m: (value: Stitches.PropertyValue<"margin">) => ({
      margin: value,
    }),
    mt: (value: Stitches.PropertyValue<"marginTop">) => ({
      marginTop: value,
    }),
    mr: (value: Stitches.PropertyValue<"marginRight">) => ({
      marginRight: value,
    }),
    mb: (value: Stitches.PropertyValue<"marginBottom">) => ({
      marginBottom: value,
    }),
    ml: (value: Stitches.PropertyValue<"marginLeft">) => ({
      marginLeft: value,
    }),
    mx: (value: Stitches.PropertyValue<"marginLeft">) => ({
      marginLeft: value,
      marginRight: value,
    }),
    my: (value: Stitches.PropertyValue<"marginTop">) => ({
      marginTop: value,
      marginBottom: value,
    }),

    userSelect: (value: Stitches.PropertyValue<"userSelect">) => ({
      WebkitUserSelect: value,
      userSelect: value,
    }),

    size: (value: Stitches.PropertyValue<"width">) => ({
      width: value,
      height: value,
    }),

    appearance: (value: Stitches.PropertyValue<"appearance">) => ({
      WebkitAppearance: value,
      appearance: value,
    }),
    backgroundClip: (value: Stitches.PropertyValue<"backgroundClip">) => ({
      WebkitBackgroundClip: value,
      backgroundClip: value,
    }),

    // LEGACY, please don't use them
    as: (value: Stitches.PropertyValue<"alignSelf">) => ({ alignSelf: value }),
    fg: (value: Stitches.PropertyValue<"flexGrow">) => ({ flexGrow: value }),
    bc: (value: Stitches.PropertyValue<"backgroundColor">) => ({
      backgroundColor: value,
    }),
  },
});

type VariblesValues = typeof config.theme;

type VariblesNames = {
  [GroupKey in keyof VariblesValues]: {
    [VariableKey in keyof VariblesValues[GroupKey]]: string;
  };
};

const toVariblesNames = (values: VariblesValues): VariblesNames => {
  const result: Record<string, Record<string, string>> = {};
  for (const groupKey in values) {
    const group = values[groupKey as keyof VariblesValues];
    const groupResult: Record<string, string> = {};
    for (const variableKey in group) {
      groupResult[variableKey] = `$${groupKey}$${variableKey}`;
    }
    result[groupKey] = groupResult;
  }
  return result as VariblesNames;
};

export const theme = toVariblesNames(config.theme);

export const rawTheme = config.theme;

export type CSS = Stitches.CSS<typeof config>;

export { styled, css, globalCss, keyframes, config };

export const flushCss = () => {
  const css = getCssText();
  reset();
  return css;
};

export const darkTheme = createTheme({
  colors: {
    ...grayDark,
    ...mauveDark,
    ...slateDark,
    ...sageDark,
    ...oliveDark,
    ...sandDark,
    ...tomatoDark,
    ...redDark,
    ...crimsonDark,
    ...pinkDark,
    ...plumDark,
    ...purpleDark,
    ...violetDark,
    ...indigoDark,
    ...blueDark,
    ...skyDark,
    ...mintDark,
    ...cyanDark,
    ...tealDark,
    ...greenDark,
    ...grassDark,
    ...limeDark,
    ...yellowDark,
    ...amberDark,
    ...orangeDark,
    ...brownDark,
    ...bronzeDark,
    ...goldDark,

    ...grayDarkA,
    ...mauveDarkA,
    ...slateDarkA,
    ...sageDarkA,
    ...oliveDarkA,
    ...sandDarkA,
    ...tomatoDarkA,
    ...redDarkA,
    ...crimsonDarkA,
    ...pinkDarkA,
    ...plumDarkA,
    ...purpleDarkA,
    ...violetDarkA,
    ...indigoDarkA,
    ...blueDarkA,
    ...skyDarkA,
    ...mintDarkA,
    ...cyanDarkA,
    ...tealDarkA,
    ...greenDarkA,
    ...grassDarkA,
    ...limeDarkA,
    ...yellowDarkA,
    ...amberDarkA,
    ...orangeDarkA,
    ...brownDarkA,
    ...bronzeDarkA,
    ...goldDarkA,

    // Semantic colors
    hiContrast: "$slate12",
    loContrast: "hsl(0 0% 17%)",
    hint: "$slate9",
    muted: "$slate8",
    primary: "$blue10",
    canvas: "hsl(0 0% 15%)",
    panel: "$slate2",
    backgroundPanel: "$slate2",
    backgroundMenu: "$slate2",
    backgroundControls: "$slate3",
    backgroundPresetMain: "$slate5",
    backgroundHover: "$slate6",
    backgroundCanvas: "$slate5",
    borderMain: "$slate5",
    borderNeutral: "$slate4",
    backgroundNeutralMain: "$slate4",
    foregroundMain: "$slate11",
    backgroundItemMenuItemHover: "$slate6",
    panelOutline: "hsl(0deg 0% 100% / 10%)",
    transparentPanel: "hsl(0 100% 100% / 97%)",
    shadowLight: "hsl(206 22% 7% / 35%)",
    shadowDark: "hsl(206 22% 7% / 20%)",
    background: "$slate12",
    text: "$slate1",
    foregroundFlexUiMain: "$slate9",
    backgroundPresetHover: "$slate6",
    backgroundSpacingLeftRight: "$slate4",
    backgroundSpacingHover: "$slate6",
    foregroundIconMain: "$slate11",
    backgroundLocalMain: "$blueA6",
    backgroundLocalHover: "$blue4",
    borderLocalMain: "$slate6",
    foregroundLocalMain: "$blueA11",
    foregroundRemoteMain: "$orangeA11",
    backgroundRemoteMain: "$orangeA3",
    borderRemoteMain: "$orange4",
    backgroundButtonDisabled: "$slate8",

    // TODO: (#Webtir) The following are the default colors for the light mode
    // The ones that are commented out are adjusted to satisfy the dark mode
    // Other ones have to be adjusted as well
    white: "#ffffff",
    black: "#000000",
    //backgroundPanel: "#f8f8f8",
    backgroundPrimary: "#096cff",
    //backgroundHover: "#dfe3e6",
    backgroundActive: "#096cff",
    //backgroundMenu: "#ededed",
    //backgroundControls: "#ffffff",
    backgroundAssetcardHover: "#e6e8eb",
    //backgroundNeutralMain: "#d7dbdf",
    backgroundNeutralAccent: "#11181c",
    backgroundNeutralNotification: "#ffffff",
    backgroundNeutralDark: "#7e868c",
    backgroundDestructiveMain: "#dc2929",
    backgroundDestructiveNotification: "#ffefef",
    backgroundSuccessMain: "#00894a",
    backgroundSuccessNotification: "#e9f9ee",
    backgroundAlertMain: "#f5d90a",
    backgroundAlertNotification: "#fffbd1",
    backgroundInfoMain: "#0175dc",
    backgroundInfoNotification: "#edf6ff",
    //backgroundPresetMain: "#e6e8eb",
    //backgroundPresetHover: "#dfe3e6",
    //backgroundLocalMain: "#e1f0ff",
    //backgroundLocalHover: "#cee7fe",
    //backgroundRemoteMain: "#ffe8d7",
    backgroundRemoteHover: "#ffdcc3",
    backgroundInputSelected: "#b7d9f8",
    backgroundInputDisabled: "#f8f8f8",
    backgroundInputHighlight: "#b7d9f8",
    backgroundButtonHover: "#ffffff17",
    backgroundButtonPressed: "#0000001c",
    //backgroundButtonDisabled: "#e9ebed",
    backgroundItemCurrent: "#096cff",
    backgroundItemCurrentChild: "#e1f0ff",
    backgroundItemCurrentHidden: "#7e868c",
    //backgroundItemMenuItemHover: "#d3d3d3",
    backgroundTooltipMain: "#11181c",
    backgroundTooltipBuilder: "#ffffff",
    backgroundTooltipDesigner: "#ffffff",
    backgroundSpacingTopBottom: "#f1f3f5",
    //backgroundSpacingLeftRight: "#f1f3f5",
    //backgroundSpacingHover: "#d7dbdf",
    backgroundStyleSourceToken: "#096cff",
    backgroundStyleSourceTag: "#d54113",
    backgroundStyleSourceState: "#00894a",
    backgroundStyleSourceNeutral: "#687076",
    backgroundStyleSourceDisabled: "#9da2a6",
    backgroundStyleSourceGradientToken:
      "linear-gradient(90deg, #096cff00 0%, #096cff 31.87%)",
    backgroundStyleSourceGradientTag:
      "linear-gradient(90deg, #d5411300 0%, #d54113 31.87%)",
    backgroundStyleSourceGradientUnselected:
      "linear-gradient(90deg, #68707600 0%, #687076 31.87%)",
    backgroundStyleSourceBreakpoint: "#bd2fdb",
    //backgroundCanvas: "#c7c7c7",
    backgroundTopbar: "#2d2d2d",
    backgroundGradientPrimary:
      "linear-gradient(135deg, #1774ff 0%, #bd2fdb 100%)",
    backgroundGradientVertical:
      "linear-gradient(180deg, #096cff 0%, #096cff 0.01%, #bd2fdb 100%)",
    backgroundGradientHorizontal:
      "linear-gradient(90deg, #4a4efa 0%, #bd2fdb 100%)",
    backgroundGradientHorizontalReverse:
      "linear-gradient(90deg, #bd2fdb 0%, #4a4efa 100%)",
    backgroundMenuHint: "#dedede",
    backgroundTopbarHover: "#383838",
    backgroundWorkspace: "#a9a9a9",
    backgroundIconSubtle: "#3e3e3e",
    backgroundPrimaryLight: "#2e82ff",
    backgroundOverwrittenMain: "#ffd9d9",
    backgroundOverwrittenHover: "#fec4c4",
    brandBackgroundProjectCardFront:
      "linear-gradient(0deg, #fbf8ff 0%, #e2e2e2 100%)",
    brandBackgroundProjectCardBack:
      "linear-gradient(0deg, #fbf8ff 0%, #c7c7c7 100%)",
    brandBackgroundProjectCardTextArea: "#ffffff",
    brandBackgroundPublishedMain: "#39fbbb",
    brandBackgroundGradient:
      "linear-gradient(180deg, #e63cfe 0%, #ffae3c 100%)",
    brandBackgroundPublishedContrast: "#ebfffc",
    brandBackgroundDashboard: "#ededed",
    brandBackgroundRegularButtonSelected:
      "linear-gradient(180deg, #bffeec 0%, #fbfff6 100%)",
    brandBackgroundCtaButton:
      "linear-gradient(135deg, #4a4efa 0%, #bd2fdb 100%)",
    brandForegroundPublished: "#00894a",
    brandBorderPublished: "#ebfffc",
    brandBorderFullGradient:
      "linear-gradient(135deg, #92fddc 0%, #7d7ffb 31.94%, #ed72fe 64.24%, #fdd791 100%)",
    brandBorderNavbar:
      "linear-gradient(90deg, #39fbbb00 0%, #39fbbb 20%, #4a4efa 40.03%, #e63cfe 60.02%, #ffae3c 80.04%, #ffae3c00 100%, #ffae3c00 100%)",
    brandSpinnerTurquoise: "#39fbbb",
    brandSpinnerBlue: "#4a4efa",
    brandSpinnerPurple: "#e63cfe",
    brandSpinnerOrange: "#ffae3c",
    //borderMain: "#c1c8cd",
    borderFocus: "#096cff",
    borderMenuInner: "#fcfcfc",
    borderColorSwatch: "#687076",
    //borderNeutral: "#e8e8e8",
    borderSuccess: "#00894a",
    borderAlert: "#e2c802",
    borderInfo: "#096cff",
    borderContrast: "#ffffff",
    borderItemChildLine: "#889096",
    borderItemChildLineCurrent: "#96c7f2",
    //borderLocalMain: "#b7d9f8",
    borderLocalFlexUi: "#096cff",
    //borderRemoteMain: "#fbc69f",
    borderRemoteFlexUi: "#fa934e",
    borderDestructiveMain: "#d13a3a",
    borderDestructiveNotification: "#f9c6c6",
    borderDark: "#595c5d",
    borderOverwrittenMain: "#fdaaab",
    borderOverwrittenFlexUi: "#dc3d43",
    borderPrimary: "#096cff",
    //foregroundMain: "#11181c",
    foregroundSubtle: "#707375",
    foregroundCategoryLabel: "#889096",
    foregroundTextSubtle: "#687076",
    foregroundDestructive: "#d13a3a",
    foregroundSuccess: "#00b661",
    foregroundInfo: "#096cff",
    foregroundDisabled: "#c1c8cd",
    foregroundHiddenItem: "#7e868c",
    //foregroundFlexUiMain: "#c7c7c7",
    foregroundFlexUiHover: "#96c7f2",
    foregroundContrastMain: "#ffffff",
    foregroundContrastSubtle: "#c1c8cd",
    //foregroundLocalMain: "#016ccc",
    foregroundLocalFlexUi: "#237cff",
    //foregroundRemoteMain: "#b74900",
    foregroundRemoteFlexUi: "#fa934e",
    foregroundTextMoreSubtle: "#8d949a",
    foregroundPrimary: "#096cff",
    foregroundSuccessText: "#008447",
    foregroundGridControlsDot: "#c7c7c7",
    foregroundGridControlsDotHover: "#707375",
    foregroundGridControlsFlexHover: "#96c7f2",
    // foregroundIconSecondary: "#c1c8cd",
    // foregroundIconMain: "#11181c",
    foregroundMoreSubtle: "#adb1b4",
    foregroundScrollBar: "#a7acaf99",
    foregroundOverwrittenMain: "#bf0007",
    foregroundOverwrittenFlexUi: "#dc3d43",
    foregroundInversePrimary: "#ff22ae",
    maintenanceLight: "#ededed",
    maintenanceMedium: "#c7c7c7",
    maintenanceDark: "#858585",
    maintenanceSpacerViz: "#f9c6c6",
    backgrondMenuHint: "#dedede",
  },
});
